export enum TransactionType {
    DEPOSIT="DEPOSIT",
    WITHDRAWAL="WITHDRAWAL",
    TRANSFER="TRANSFER",
    INTEREST="INTEREST",
    TRANSFER_TO_LOAN="TRANSFER_TO_LOAN",
    TRANSFER_FROM_LOAN="TRANSFER_FROM_LOAN",
    
   
}
