export enum TransactionType {
    DEPOSIT="DEPOSIT",
    WITHDRAWAL="WITHDRAWAL",
    TRANSFER="TRANSFER",
    INTEREST="INTEREST",
    TRANSFER_TO_LOAN="TRANSFER_TO_LOAN",
    TRANSFER_FROM_LOAN="TRANSFER_FROM_LOAN",
    TRANSFER_OUT = "TRANSFER_OUT",
    TRANSFER_IN = "TRANSFER_IN",
    TRANSFER_INCOMING = "TRANSFER_INCOMING",
    ATM_WITHDRAWAL = "ATM_WITHDRAWAL",
    TAX_WITHDRAWAL = "TAX_WITHDRAWAL",
    
   
}
